### ISSUE TITLE
Hipchat don't work

### ISSUE THREAD

**Issue by thiencdcn** [digitalnatives/redmine_hipchat_per_project#2]
Hi, I use
Environment:
  Redmine version                          2.2.3.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.12
  Environment                              production
  Database adapter                         Mysql2

and Hipchat don't work, please update.
thanks!!!

**Comment by zosiu** [comment]
Check out the redmine2 branch (https://github.com/digitalnatives/redmine_hipchat_per_project/tree/redmine2), it should work now.
